# fly.toml app configuration file generated for keylink-relay on 2025-06-11T16:15:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'keylink-relay'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 20801
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[env]
  ENABLE_UDP = "false"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
